version: '3.8'
services:
    api-gateway:
        build:
            context: './api-gateway'
            dockerfile: 'Dockerfile'
        env_file:
            - ./api-gateway/.env
        depends_on:
            - users-service
            - banners-service
            - image-delivery-service
            - profiles-service
            - discounts-service
            - rabbitmq
        ports:
            - '80:8080'
    users-service:
        build:
            context: './users-service'
            dockerfile: 'Dockerfile'
        env_file:
            - ./users-service/.env
        depends_on:
            - users-service-db
            - rabbitmq
    banners-service:
        build:
            context: './banners-service'
            dockerfile: 'Dockerfile'
        env_file:
            - ./banners-service/.env
        depends_on:
            - banners-service-db
            - image-delivery-service
            - rabbitmq
    profiles-service:
        build:
            context: './profiles-service'
            dockerfile: 'Dockerfile'
        env_file:
            - ./profiles-service/.env
        depends_on:
            - profiles-service-db
            - image-delivery-service
            - rabbitmq
        command: sh -c '/bin/wait-for-it.sh rabbitmq:5672 --timeout=60 -- npm run start'
    discounts-service:
        build:
            context: './discounts-service'
            dockerfile: 'Dockerfile'
        env_file:
            - ./discounts-service/.env
        depends_on:
            - discounts-service-db
            - image-delivery-service
            - rabbitmq
    image-delivery-service:
        build:
            context: './image-delivery-service'
            dockerfile: 'Dockerfile.dev'
        depends_on:
            - rabbitmq
        ports:
            - '8085:8080'
    users-service-db:
        image: mongo
        ports:
            - '27018:27017'
        volumes:
            - ./users-service/db:/data/db
    banners-service-db:
        image: mongo
        ports:
            - '27019:27017'
        volumes:
            - ./banners-service/db:/data/db
    profiles-service-db:
        image: mongo
        ports:
            - '27020:27017'
        volumes:
            - ./profiles-service/db:/data/db
    discounts-service-db:
        image: mongo
        ports:
            - '27021:27017'
        volumes:
            - ./discounts-service/db:/data/db
    rabbitmq:
        image: rabbitmq:3.11-management-alpine
        container_name: 'rabbitmq'
        ports:
            - '5672:5672'
            - '15672:15672'
