version: '3.8'
services:
    api-gateway:
        build:
            context: './api-gateway'
            dockerfile: 'Dockerfile'
        depends_on:
            - users-service
            - banners-service
        ports:
            - '7070:7070'
        volumes:
            - ./api-gateway:/app
    users-service:
        build:
            context: './users-service'
            dockerfile: 'Dockerfile'
        depends_on:
            - users-service-db
        ports:
            - '7071:7071'
        volumes:
            - ./users-service:/app
    banners-service:
        build:
            context: './banners-service'
            dockerfile: 'Dockerfile'
        depends_on:
            - banners-service-db
        ports:
            - '7072:7072'
        volumes:
            - './banners-service:/app'
    categories-service:
        build:
            context: './categories-service'
            dockerfile: 'Dockerfile'
        depends_on:
            - categories-service-db
        ports:
            - '7073:7073'
        volumes:
            - './categories-service:/app'
    profiles-service:
        build:
            context: './profiles-service'
            dockerfile: 'Dockerfile'
        depends_on:
            - profiles-service-db
        ports:
            - '7074:7074'
        volumes:
            - './profiles-service:/app'
    users-service-db:
        image: mongo
        volumes:
            - ./users-service/data:/data/db
        ports:
            - '27018:27017'
    banners-service-db:
        image: mongo
        volumes:
            - ./banners-service/data:/data/db
        ports:
            - '27019:27017'
    categories-service-db:
        image: mongo
        volumes:
            - ./categories-service/data:/data/db
        ports:
            - '27020:27017'
    profiles-service-db:
        image: mongo
        volumes:
            - ./profiles-service/data:/data/db
        ports:
            - '27021:27017'
