version: '3.8'
services:
    api-gateway:
        build:
            context: './api-gateway'
            dockerfile: 'Dockerfile.dev'
        env_file:
            - ./api-gateway/.env
        depends_on:
            - users-service
            - banners-service
            - categories-service
            - profiles-service
            - sections-service
            - discounts-service
        ports:
            - '8080:8080'
        volumes:
            - ./api-gateway/src:/app/src
    users-service:
        build:
            context: './users-service'
            dockerfile: 'Dockerfile.dev'
        env_file:
            - ./users-service/.env
        depends_on:
            - users-service-db
        ports:
            - '8081:8080'
        volumes:
            - ./users-service/src:/app/src
    banners-service:
        build:
            context: './banners-service'
            dockerfile: 'Dockerfile.dev'
        depends_on:
            - banners-service-db
        ports:
            - '8082:8080'
        volumes:
            - './banners-service/src:/app/src'
    categories-service:
        build:
            context: './categories-service'
            dockerfile: 'Dockerfile.dev'
        depends_on:
            - categories-service-db
        ports:
            - '8083:8080'
        volumes:
            - './categories-service/src:/app/src'
    profiles-service:
        build:
            context: './profiles-service'
            dockerfile: 'Dockerfile.dev'
        depends_on:
            - profiles-service-db
        ports:
            - '8084:8080'
        volumes:
            - './profiles-service/src:/app/src'
    sections-service:
        build:
            context: './sections-service'
            dockerfile: 'Dockerfile.dev'
        depends_on:
            - sections-service-db
        ports:
            - '8085:8080'
        volumes:
            - './sections-service/src:/app/src'
    discounts-service:
        build:
            context: './discounts-service'
            dockerfile: 'Dockerfile.dev'
        depends_on:
            - discounts-service-db
        ports:
            - '8086:8080'
        volumes:
            - './discounts-service/src:/app/src'
    users-service-db:
        image: mongo
        volumes:
            - ./users-service/data:/data/db
        ports:
            - '27018:27017'
    banners-service-db:
        image: mongo
        volumes:
            - ./banners-service/data:/data/db
        ports:
            - '27019:27017'
    categories-service-db:
        image: mongo
        volumes:
            - ./categories-service/data:/data/db
        ports:
            - '27020:27017'
    profiles-service-db:
        image: mongo
        volumes:
            - ./profiles-service/data:/data/db
        ports:
            - '27021:27017'
    sections-service-db:
        image: mongo
        volumes:
            - ./sections-service/data:/data/db
        ports:
            - '27022:27017'
    discounts-service-db:
        image: mongo
        volumes:
            - ./discounts-service/data:/data/db
        ports:
            - '27023:27017'
